// Code generated by counterfeiter. DO NOT EDIT.
package mock

import (
	"sync"

	"github.com/wlahti/lp/server"
)

type NotesGetter struct {
	GetNotesStub        func(int) []string
	getNotesMutex       sync.RWMutex
	getNotesArgsForCall []struct {
		arg1 int
	}
	getNotesReturns struct {
		result1 []string
	}
	getNotesReturnsOnCall map[int]struct {
		result1 []string
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *NotesGetter) GetNotes(arg1 int) []string {
	fake.getNotesMutex.Lock()
	ret, specificReturn := fake.getNotesReturnsOnCall[len(fake.getNotesArgsForCall)]
	fake.getNotesArgsForCall = append(fake.getNotesArgsForCall, struct {
		arg1 int
	}{arg1})
	fake.recordInvocation("GetNotes", []interface{}{arg1})
	fake.getNotesMutex.Unlock()
	if fake.GetNotesStub != nil {
		return fake.GetNotesStub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.getNotesReturns
	return fakeReturns.result1
}

func (fake *NotesGetter) GetNotesCallCount() int {
	fake.getNotesMutex.RLock()
	defer fake.getNotesMutex.RUnlock()
	return len(fake.getNotesArgsForCall)
}

func (fake *NotesGetter) GetNotesCalls(stub func(int) []string) {
	fake.getNotesMutex.Lock()
	defer fake.getNotesMutex.Unlock()
	fake.GetNotesStub = stub
}

func (fake *NotesGetter) GetNotesArgsForCall(i int) int {
	fake.getNotesMutex.RLock()
	defer fake.getNotesMutex.RUnlock()
	argsForCall := fake.getNotesArgsForCall[i]
	return argsForCall.arg1
}

func (fake *NotesGetter) GetNotesReturns(result1 []string) {
	fake.getNotesMutex.Lock()
	defer fake.getNotesMutex.Unlock()
	fake.GetNotesStub = nil
	fake.getNotesReturns = struct {
		result1 []string
	}{result1}
}

func (fake *NotesGetter) GetNotesReturnsOnCall(i int, result1 []string) {
	fake.getNotesMutex.Lock()
	defer fake.getNotesMutex.Unlock()
	fake.GetNotesStub = nil
	if fake.getNotesReturnsOnCall == nil {
		fake.getNotesReturnsOnCall = make(map[int]struct {
			result1 []string
		})
	}
	fake.getNotesReturnsOnCall[i] = struct {
		result1 []string
	}{result1}
}

func (fake *NotesGetter) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getNotesMutex.RLock()
	defer fake.getNotesMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *NotesGetter) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ server.NotesGetter = new(NotesGetter)
